#!/usr/bin/env bash
# Bash script for transferring a file from a client to a server using the scp Linux command.
# Parameters:
#   $1: PATH_TO_FILE - Path to the file to be copied to the server.
#   $2: IP - IP address of the server.
#   $3: USERNAME - Username on the server.
#   $4: PATH_TO_SSH_KEY - Path to the SSH private key for user authentication.

if [ $# -lt 4 ]; then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi
