#!/usr/bin/env bash
# Installs nginx server on ubuntu.
# Server listens to port 80 (HTTP)
# Serves index.html on the HTTP  GET request as a default page.

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
