#!/bin/bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Configure redirection for /redirect_me
sudo sh -c 'echo "
server {
    listen 80;

    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional server configuration...
}
" > /etc/nginx/sites-available/redirect_me'

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload
