#!/usr/bin/env bash
# Installs Nginx server and redirects to my github account /redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello world" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/tshegofatsoseane permanent;/" /etc/nginx/sites-available/default
service nginx start
