#!/usr/bin/env bash
#  Install HAProxy with these configurations:
# - Enable management via the init script.
# - Distribute requests using the round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend tshego.tech
    timeout client  30000
    bind 0:80
    default_backend tshego.tech_backend

backend tshego.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 339153-web-01 34.229.189.51:80 check
    server 339153-web-02 54.197.22.41:80 check
EOT

sudo service haproxy restart
