#!/usr/bin/env bash
# Fix a web server to run Nginx as the nginx user listening on port 8080.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
