#!/usr/bin/env bash
# A long bash script to manage the script manage_my_process.
#   When passed the argument `start`:
#     Start manage_my_process
#     Create a file containings its PID in /var/run/my_process.pid
#     Display "manage_my_process started"
#   When passed the argument `stop`:
#     Stop manage_my_process
#     Delete the file /var/run/my_process.pid
#     Display "manage_my_process stopped"
#   When passed the argument `restart`:
#     Stop manage_my_process
#     Delete the file /var/run/my_process.pid
#     Start manage_my_process
#     Create a file containing its PID in /var/run/my_process.pid
#     Display "manage_my_process restarted"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
