#!usr/bin/env bash
# SSH client config

Host *
    PasswordAuthentication no
    HostName 34.229.189.51
    User ubuntu
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
