#!usr/bin/env bash
# SSH client config

Host *

    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
